name: Build only

on:
  pull_request:
    branches: [ "main" ]

jobs:

  push_to_registry:
    name: Build Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }},lopf/rundeck-extended:latest
          labels: ${{ steps.meta.outputs.labels }}
